"""Compatibility exports for DNS argument and result models."""

from seedemu_tool_service.tools.dns.basic.models import (
    DNSLookupArguments,
    DNSLookupDetails,
    DNSLookupResult,
    DNSReverseLookupArguments,
    DNSReverseLookupResult,
)
from seedemu_tool_service.tools.dns.diagnostics.models import (
    DNSCompareArguments,
    DNSCompareDifference,
    DNSCompareResult,
    DNSCompareServerResult,
    DNSDelegationArguments,
    DNSDelegationChildResult,
    DNSDelegationResult,
    DNSTraceArguments,
    DNSTraceResult,
    DNSTraceStep,
)
from seedemu_tool_service.tools.dns.domain_registration.models import (
    DNSConfigureArguments,
    DNSConfigureOperation,
    DNSConfigureResult,
    DNSRecordChange,
    DNSServiceLocation,
    RegistrarFindArguments,
    RegistrarFindResult,
    RegistrarLocation,
    RegistrarRequestArguments,
    RegistrarRequestMethod,
    RegistrarRequestResult,
)
from seedemu_tool_service.tools.dns.shared.models import (
    DNSRecord,
    DNSRecordType,
    ToolArguments,
)

__all__ = [
    "DNSCompareArguments",
    "DNSCompareDifference",
    "DNSCompareResult",
    "DNSCompareServerResult",
    "DNSDelegationArguments",
    "DNSDelegationChildResult",
    "DNSDelegationResult",
    "DNSLookupArguments",
    "DNSLookupDetails",
    "DNSLookupResult",
    "DNSRecord",
    "DNSRecordType",
    "DNSReverseLookupArguments",
    "DNSReverseLookupResult",
    "DNSTraceArguments",
    "DNSTraceResult",
    "DNSTraceStep",
    "DNSConfigureArguments",
    "DNSConfigureOperation",
    "DNSConfigureResult",
    "DNSRecordChange",
    "DNSServiceLocation",
    "RegistrarFindArguments",
    "RegistrarFindResult",
    "RegistrarLocation",
    "RegistrarRequestArguments",
    "RegistrarRequestMethod",
    "RegistrarRequestResult",
    "ToolArguments",
]
